/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_LOTTIE_FILES           3
#define MMAP_LOTTIE_CHECKSUM        0x0723

enum MMAP_LOTTIE_LISTS {
    MMAP_LOTTIE_COFFEE_JSON = 0,        /*!< coffee.json */
    MMAP_LOTTIE_HAND_JSON = 1,        /*!< hand.json */
    MMAP_LOTTIE_WELCOME_JSON = 2,        /*!< welcome.json */
};
